### ISSUE TITLE
How do you ignore a test?

### ISSUE THREAD

**Issue by vext01** [softdevteam/ykbf#10]
I was expecting to be able to put `// ignore: blah` at the top of a test file, but this didn't work.

Looks like we have to teach lang tester how to extract such lines?

**Comment by ltratt** [comment]
This *should* work, though obviously I don't know the precise details. If it doesn't, please file an issue against lang_tester, as it's not a ykbf issue.

**Comment by vext01** [comment]
I'm not sure it's a langtester bug.

I think that [this driver code](https://github.com/softdevteam/ykbf/blob/c5a7f4e4ce8cd571f66ec7ae71d72dcb2da1d4c5/lang_tests/run.rs#L16) needs to be taught what a bf comment is, so that lang tester can find magic comments like `ignore`?

Like [this](https://github.com/softdevteam/lang_tester/blob/72da79347e7e42040a84c4e3937b003de04d8bfb/examples/rust_lang_tester/run_tests.rs#L25-L31)?

I may be wrong.

**Comment by ltratt** [comment]
We've moved this to a more appropriate discussion forum.
